# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Profess' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Profess
pod 'Alamofire', '5.1'

  target 'ProfessTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ProfessUITests' do
    # Pods for testing
  end

# 필요한 모듈 추가
pod 'KakaoSDKCommon'  # 필수 요소를 담은 공통 모듈
pod 'KakaoSDKAuth'  # 사용자 인증
pod 'KakaoSDKUser'  # 카카오 로그인, 사용자 관리
pod 'KakaoSDKTalk'  # 친구, 메시지(카카오톡)
pod 'KakaoSDKLink'  # 메시지(카카오링크)

end
