# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Profess' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Profess

  target 'ProfessTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ProfessUITests' do
    # Pods for testing
	pod 'Alamofire', '5.1'
  end

end
